sudo: false

language: go

go:
  - 1.9.x
  - 1.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get github.com/gosimple/slug

script:
  - go test -v -race ./...
